config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get '/not_found', to: "errors#not_found", via: :all
  get '/internal_server_error', to: "errors#not_found", via: :all

  devise_for :users

  root 'static_pages#index'
  get '/schools', to: 'schools#index', as: 'schools'
  get '/schools/:id', to: 'schools#show', as: 'school'
  resources :courses, only: [:index, :show]
  resources :posts, only: [:show]
  get 'join_courses/:id', to: 'join_courses#create', as: 'join_course'
  resources :students
  namespace 'admin' do
    get 'dashboard', to: 'dashboard#index'
    resources :schools
    resources :posts
    resources :lessons, only: [:show]
    resources :courses do
      resources :lessons
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :duration, :price, presence: true
  validates :price, numericality: { only_float: true, greater_than: 0.0 }

  has_many :lessons
  has_many :course_enrollments
  has_many :students, through: :course_enrollments
  belongs_to :school

end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student, :course, associated: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  scope :is_published, -> { where('published is true') }
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user
  has_many :courses
  validates :name, uniqueness: true, presence: true
  validates :pitch, :foundation,:subdomain, presence: true
  validates :email, presence: true, format: Devise.email_regexp
  validates :subdomain, format: { with: /\A\w+\.(edools.com)\z/i }

  scope :by_name, ->(name) { where('lower(name) LIKE ?', "%#{name}%") }
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, :last_name, :birthdate, presence: true
  validates :age, :rg, presence: true, numericality: { only_integer: true, greater_than: 0 }

  belongs_to :user

  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :school
  has_one :student
  has_many :posts

  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.is_published.order_by(:created_at).desc
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render '/shared/navbar_top' %>

    <%= yield %>


    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<br/>
<div class="row">
  <p class="notice"><%= notice %> </p>
  <p class="alert"><%= alert %></p>
</div>

app/views/shared/_main_body.html.erb
<% if user_signed_in? %>
  <%=link_to 'logout', destroy_user_session_url, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/shared/_navbar_top.html.erb
<nav class="navbar navbar-default" id="change-color">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SysSchool', root_path, class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="active"><%= link_to ' Home', root_path%></li>
        <!--
        <li><%= link_to 'About', static_pages_about_url%></li>
        <li>
          <%= link_to 'Contact', static_pages_contact_url %> 
        </li> 
        -->
        <li>
          <%= link_to 'Listar Cursos', courses_url %>
        </li>
        <li>
          <%= link_to 'Listar Escolas', schools_url %>
        </li>
        <li>
          <% if !current_user.nil? and current_user.is_admin? %>
            <%= link_to 'DashBoard', admin_dashboard_path %>
          <% end%>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_url, method: :delete %>
          <% else %>
            <%= link_to 'Login', new_user_session_url %>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>