config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get '/not_found', to: "errors#not_found", via: :all
  get '/internal_server_error', to: "errors#not_found", via: :all

  devise_for :users

  root 'static_pages#index'
  get '/schools', to: 'schools#index', as: 'schools'
  get '/schools/:id', to: 'schools#show', as: 'school'
  resources :courses, only: [:index, :show]
  resources :posts, only: [:show]
  get 'join_courses/:id', to: 'join_courses#create', as: 'join_course'
  resources :students
  namespace 'admin' do
    get 'dashboard', to: 'dashboard#index'
    resources :schools
    resources :posts
    resources :lessons, only: [:show]
    resources :courses do
      resources :lessons
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :duration, :price, presence: true
  validates :price, numericality: { only_float: true, greater_than: 0.0 }

  has_many :lessons
  has_many :course_enrollments
  has_many :students, through: :course_enrollments
  belongs_to :school

end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student, :course, associated: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  scope :is_published, -> { where('published is true') }
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user
  has_many :courses
  validates :name, uniqueness: true, presence: true
  validates :pitch, :foundation,:subdomain, presence: true
  validates :email, presence: true, format: Devise.email_regexp
  validates :subdomain, format: { with: /\A\w+\.(edools.com)\z/i }

  scope :by_name, ->(name) { where('lower(name) LIKE ?', "%#{name}%") }
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, :last_name, :birthdate, presence: true
  validates :age, :rg, presence: true, numericality: { only_integer: true, greater_than: 0 }

  belongs_to :user

  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :school
  has_one :student
  has_many :posts

  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
end

app/controllers/admin/schools_controller.rb
module Admin
  class SchoolsController < AdminController
    before_action :set_school, only: [:show, :edit, :update, :destroy]
    def index
      @schools = current_user.school
    end

    def new
      if !current_user.school
        @school = School.new
      end
    end

    def create
      @school = current_user.build_school(school_params)
      if @school.save
        redirect_to admin_school_url(@school)
      else
        render 'new'
      end
    end

    def show; end

    def edit; end

    def update
      if @school.update(school_params)
        flash[:notice] = 'Escola atualizada com sucesso.'
        redirect_to admin_schools_url
      else
        render 'edit'
      end
    end

    private

    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :subdomain, :foundation,
                                     :email, :pitch)
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :join_course]
  before_action :authenticate_user!, only: [:show]

  def index
    @c = Course.search(params[:q])
    @courses = @c.result.page params['page']
  end

  def show ; end

  private

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.is_published.order_by(:created_at).desc
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show]
  before_action :authenticate_user!, only: [:show]
  def index
    @search = School.search(params[:q])
    @schools = @search.result.page params['page']
  end

  def show
    @search_course = @school.courses.search(params[:q])
    @results = @search_course.result
  end

  private
  def set_school
    @school = School.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Students.all
  end
  
  def new
    @student = Student.new
  end

  def create
    @student = current_user.build_student(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render 'new'
    end
  end

  def show ; end

  def edit ; end

  def update
  end
  
  def destroy
  end

  private
  def set_student
  end

  def student_params
    params.require(:student).permit(:rg, :age, :birthdate, :last_name, :first_name)
  end
end

app/helpers/admin/schools_helper.rb
module Admin::SchoolsHelper
  def active_students(school)
    active = 0
    school.courses.each do |course|
      active = active + course.students.count
    end
    active
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/schools/_form.html.erb
<%= simple_form_for @school, url: admin_schools_url do |f| %>
  <% if @school.errors.any? %>
    <h2><%= pluralize(@school.errors.count, 'erro encontrado')%>:</h2>
    <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :pitch %>
  <%= f.input :subdomain %>
  <%= f.input :foundation, as: :date %>
  <%= f.submit 'enviar', class:'btn btn-success' %>
  <%= link_to 'voltar', admin_schools_path, class:'btn btn-default'%>
<% end %>

app/views/admin/schools/edit.html.erb
<div class="container">
  <h1>Edit current school if already created</h1>

  <%= render 'form' %>
</div>

app/views/admin/schools/index.html.erb
<div class="container">
  <h1>this is a index page for admini school</h1>

  <% if !@schools.nil? %>
    <%= @schools.name %>
    <%= @schools.foundation %>
    <%= @schools.email %>
    <%= @schools.pitch %>
    <h2>Alunos Ativos: <%= active_students(@schools) %></h2>
    <br/>
    <%= link_to 'editar escola', edit_admin_school_url(@schools.id), class:'btn btn-primary' %>
  <% else %>
    <%= link_to 'Nova escola', new_admin_school_path, class:'btn btn-default' %>
  <% end %>

  <%= link_to 'voltar', admin_dashboard_path, class:'btn btn-default' %>
</div>

app/views/admin/schools/new.html.erb
<div class="container">
  <p class="alert"><%= alert %></p>
  <h1>The new school if schools do not exist for current user</h1>

  <%= render partial: 'form', locals: {button_label: 'Nova escola', school: @school} %>
  </br>
  <%= link_to 'voltar', admin_dashboard_path, class:"btn btn-primary" %>
</div>

app/views/admin/schools/show.html.erb
<div class="container">
  <table class="table table-striped" id="change-link-style">"
    <thead>
      <tr>
        <th>#</th>
        <th>Escola</th>
        <th>Detalhes</th>
        <th> Ações </th>
      </tr>
    </thead>
    <tr>
      <td><%= @school.name %></td>
      <td><%= @school.pitch %></td>
      <td><%= @school.email %>
      <td><%= @school.foundation %></td>
      <td><%= @school.subdomain %></td>
      <td><%= link_to 'Editar', edit_admin_school_path(@school)%>
    </tr>
  </table>
  <%= link_to 'voltar', admin_dashboard_path %>
</div>

app/views/schools/index.html.erb
<h1>Escolas Cadastradas</h1>
<div class="search-field">
  <%= search_form_for @search do |f| %>
    <%= f.search_field :name_cont, placeholder: 'Pesquisar...' %>
    <%= f.submit %>
  <% end %>
</div>
<br/>

<table class="table table-striped" id="change-link-style">
  <thead>
    <tr>
      <th>#</th>
      <th>Escola</th>
      <th>Detalhes</th>
    </tr>
  </thead>
  <% @schools.each.with_index do |school, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= school.name %></td>
      <td>
        <%= link_to("Exibir", school) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/schools/show.html.erb
<h1><%= @school.name %></h1>

<%= search_form_for @search_course do |f|%>
  <%= f.search_field :name_cont, placeholder: 'Procurar Curso...'%>
  <%= f.submit 'Pesquisar' %>
<% end %>
<% if current_user.is_admin? %>
  <h2>Quandidade de Alunos ativos: <%= active_students(@school) %></h2>
<% end %>
<h2>Cursos disponiveis: </h2>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Duração</th>
      <th>Preço</th>
      <th>Ações</th>
    </tr>
  </thead>
  <% @results.each.with_index do |course, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= course.name %></td>
      <td><%= course.duration %></td>
      <td><%= number_to_currency(course.price, unit: 'R$'  ) %></td>
      <td><%= link_to 'Mais', course_path(course) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'voltar', root_path %>