config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get '/not_found', to: "errors#not_found", via: :all
  get '/internal_server_error', to: "errors#not_found", via: :all

  devise_for :users

  root 'static_pages#index'
  get '/schools', to: 'schools#index', as: 'schools'
  get '/schools/:id', to: 'schools#show', as: 'school'
  resources :courses, only: [:index, :show]
  resources :posts, only: [:show]
  get 'join_courses/:id', to: 'join_courses#create', as: 'join_course'
  resources :students
  namespace 'admin' do
    get 'dashboard', to: 'dashboard#index'
    resources :schools
    resources :posts
    resources :lessons, only: [:show]
    resources :courses do
      resources :lessons
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :duration, :price, presence: true
  validates :price, numericality: { only_float: true, greater_than: 0.0 }

  has_many :lessons
  has_many :course_enrollments
  has_many :students, through: :course_enrollments
  belongs_to :school

end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student, :course, associated: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  scope :is_published, -> { where('published is true') }
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user
  has_many :courses
  validates :name, uniqueness: true, presence: true
  validates :pitch, :foundation,:subdomain, presence: true
  validates :email, presence: true, format: Devise.email_regexp
  validates :subdomain, format: { with: /\A\w+\.(edools.com)\z/i }

  scope :by_name, ->(name) { where('lower(name) LIKE ?', "%#{name}%") }
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, :last_name, :birthdate, presence: true
  validates :age, :rg, presence: true, numericality: { only_integer: true, greater_than: 0 }

  belongs_to :user

  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :school
  has_one :student
  has_many :posts

  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < AdminController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all
    end

    def show; end

    def new
      @post = Post.new
    end

    def edit; end

    def create
      @post = current_user.posts.new(post_params)

      if @post.save
        redirect_to admin_post_url(@post), notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to admin_post_url(@post), notice: 'Post was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      end
    end

    private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :published)
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :join_course]
  before_action :authenticate_user!, only: [:show]

  def index
    @c = Course.search(params[:q])
    @courses = @c.result.page params['page']
  end

  def show ; end

  private

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.is_published.order_by(:created_at).desc
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show]
  before_action :authenticate_user!, only: [:show]
  def index
    @search = School.search(params[:q])
    @schools = @search.result.page params['page']
  end

  def show
    @search_course = @school.courses.search(params[:q])
    @results = @search_course.result
  end

  private
  def set_school
    @school = School.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Students.all
  end
  
  def new
    @student = Student.new
  end

  def create
    @student = current_user.build_student(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render 'new'
    end
  end

  def show ; end

  def edit ; end

  def update
  end
  
  def destroy
  end

  private
  def set_student
  end

  def student_params
    params.require(:student).permit(:rg, :age, :birthdate, :last_name, :first_name)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for @post, url: admin_posts_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :published %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.published %></td>
        <td><%= link_to 'Show', admin_post_path(post) %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
        <td><%= link_to 'excluir', admin_post_path(post), method: :delete, 
          data: { confirm: 'Tem certeza que deseja excluir essa publicação?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Novo', new_admin_post_path %>
<br>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<%= link_to 'Edit', edit_admin_post_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @post.content %>
  </p>

  <%= link_to 'Back', root_path %>
</div>